# Generated by Django 4.2 on 2023-07-12 12:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('public_key', models.CharField(default=None, max_length=255)),
                ('secret_key', models.CharField(default=None, max_length=255)),
                ('webhook_secret', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
