# Generated by Django 4.2 on 2023-07-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_silly_stripe', '0002_alter_stripeconfig_public_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stripeconfig',
            options={'verbose_name': 'Stripe config', 'verbose_name_plural': 'Stripe configs'},
        ),
    ]
