# Generated by Django 4.2 on 2023-07-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_silly_stripe', '0003_alter_stripeconfig_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeconfig',
            name='restricted_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
